version: '3.8'

services:
  # Database service (PostgreSQL)
  db:
    image: postgres:15
    container_name: api-database-simple
    ports:
      - "3236:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend service (Node.js + Express)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.simple
    container_name: api-backend-simple
    ports:
      - "3350:3350"
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/main
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped
    command: npm run dev

volumes:
  postgres_data:
    driver: local 