version: '3.8'

services:
  # Backend service (Node.js + Express) - CloudType
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
      args:
        - NODE_ENV=production
    container_name: api-backend-cloudtype
    ports:
      - "3350:4000"
    environment:
      - NODE_ENV=production
      # CloudType PostgreSQL 연결 정보 (환경변수로 설정)
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - API_VERSION=${API_VERSION:-v1}
    restart: always
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    command: npm run start:prod

networks:
  app-network:
    driver: bridge 